modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/jmb05/medievalworlds/issues" #optional
[[mods]] #mandatory
modId="medievalworlds" #mandatory
version="${file.jarVersion}" #mandatory
displayName="MedievalWorlds" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="http://www.github.com/jmb05/medievalworlds/" #optional
logoFile="pack.png" #optional
credits="" #optional
authors="jmb19905" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Did you ever wanted to wield mighty weapons and rule the Minecraft world??

Well this is your chance!!!

'''
[[dependencies.medievalworlds]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.medievalworlds]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"
